name: Document Conversion

on:
  push:
    paths:
      - 'paper/**'

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p output
      - run: ls
      - uses: ./.github/actions/pandoc
        with:
          name: ${{ workspace }}/paper/index.md
          output: ./output/output.pdf
          metadata: ${{ workspace }}/paper/_output.yaml
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
