name: Document Conversion

on:
  push:
#     paths:
#       - 'paper/**'


jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo $RUNNER_OS
      - run: pwd
      - run: mkdir -p output
      - run: ls
      - run: ls paper/ -a
      - uses: sakura067m/md2pdf@master
        with:
          name: ./paper/index.md
          output: ./output/output.pdf
          metadata: ./paper/_output.yaml
      - uses: actions/upload-artifact@master
        with:
          name: $GITHUB_WORKSPACE/output/output.pdf
          path: output.pdf
