name: Document Conversion

on:
  push:
    paths:
      - 'paper/**'


jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir -p output
      - id: md2pdf
        uses: sakura067m/md2pdf@master
        with:
          pwd: paper
          name: index.md
          output: output/output.pdf
          metadata: _output.yaml
      - uses: actions/upload-artifact@master
        with:
          name: output.pdf
          path: ${{ jobs.md2pdf.outputs.path }}
