name: Document Conversion

on:
  push:
    paths:
      - 'paper/**'

jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo $RUNNER_OS
      - run: pwd
      - run: mkdir -p output
      - run: ls
      - run: ls paper/ -a
      - uses: sakura067m/md2pdf@master
        with:
          name: ./paper/index.md
          output: ./output/output.pdf
          metadata: ./paper/_output.yaml
#       - uses: actions/upload-artifact@master
#         with:
#           name: output.pdf
#           path: ./output/output.pdf
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./output/output.pdf
          asset_name: output_${{ github.ref }}.pdf
          asset_content_type: application/pdf
